[package]
name = "rustmas-light-client"
version = "0.1.0"
edition = "2021"

[dependencies]
rustmas-visualiser = { path = "../visualiser" }

async-trait = "0.1.57"
csv = "1.1.6"
reqwest = "0.11.12"
tokio = { version = "1", features = ["full"] }
