[workspace]
members = [
    "animation-api",
    "animation-macros",
    "animation-template-native",
    "animation-template-wasm",
    "animation-utils",
    "animation-wasm-wrapper",
    "animations",
    "light-client",
    "configurator",
    "animator",
    "lightfx",
    "webapi",
    "webapi-client",
    "webapi-model",
    "webui",
    "visualizer",
    "events",
    "test-wasm-animation",
]

resolver = "2"
